services:
  db:
    container_name: "postDB"
    image: postgres:16.11-alpine3.23
    volumes:
      - "./database/postgres-data:/var/lib/postgresql/data:rw"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
    restart: unless-stopped
  test_db:
    container_name: "postDB_test"
    image: postgres:16.11-alpine3.23
    volumes:
      - "./database/postgres-data-test:/var/lib/postgresql/data:rw"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
    restart: unless-stopped
